<section>
    <form action="" method="POST">
        <fieldset>
        <label>Email</label>
        <input type="text" name="email">
        </fieldset>
        
        <fieldset>
        <label>Username</label>
        <input type="text" name="username">
        </fieldset>
        
        <fieldset>
        <label>Password</label>
        <input type="password" name="password">
        </fieldset>
        
        <input type="submit" name="Modifier">
    </form>
</section>