

<section>
    <h2>Liste des Utilisateurs</h2>
    <table>
        <thead>
            <tr>
                <th>Email</th>
                <th>Username</th>
            </tr>
        </thead>
        <tbody>
            <?php 
                foreach($data['users']as $user)
                {
                    echo "<tr>";
                    echo "<td>";
                        $user->getEmail();
                    echo "</td>";
                    echo "<td>";
                        $user->getUserName();
                    echo "</td>";
                    echo "</tr>";
                }
            ?>
        </tbody>
    </table>
</section>